class GameGestureItemClass {
    public static multiple: number = 1;
    public static backGround: egret.Bitmap;
    public static scoreYou: number = 0;
    public static scoreOther: number = 0;
    public static gestureType: string;
    public static gestureScore: number = 0;
    public static mouseDBArray: Array<string> = ["GT_blue", "GT_cheng1", "GT_green", "GT_powder", "GT_red"];
    public static backGroundLight: egret.Bitmap;
    public static ScoreColumn: egret.Bitmap;
    public static headIcoLeft: RoleHeadImage;
    public static headIcoRight: RoleHeadImage;
    public static desk: egret.Bitmap;
    public static foodLeft: egret.Bitmap;
    public static foodMid: egret.Bitmap;
    public static foodRight: egret.Bitmap;
    public static leftHealthCtrlor: healthCtrlor;
    public static rightHealthCtrlor: healthCtrlor;
    public static leftHealth: number = 3;
    public static rightHealth: number = 3;
    public static readyState: Array<number> = [0, 0];
    public static isOffline: boolean;
    public static speedTime: number = 7000;
    public static lineY: number = 0;
    public static isRunning: boolean = true;
    public static resultPool: Array<number> = [0, 0];
    public static runningSec: number = 0;
    public static rightTimeDvalue: number;
    public static lowestLine: number = -10;
    public static otherlowest: number = 0;
    public static otherLine: egret.Bitmap;
    public static otherLineTW: any;
    public static AiSuccess: number = 0;
    public static autonomy: number;
    public static soundWay_1: SoundEffects;
    public static soundWay_2: SoundEffects;
    public static soundWay_3: SoundEffects;
    public static soundWay_num: number = 1;
    public static itemList: Array<any> = [];
    public static isLocal:boolean = false;

    public static dispose = () => {
        GameGestureItemClass.multiple = 1;
        GameGestureItemClass.backGround = undefined;
        GameGestureItemClass.scoreYou = 0;
        GameGestureItemClass.scoreOther = 0;
        GameGestureItemClass.gestureType = undefined;
        GameGestureItemClass.gestureScore = 0;
        GameGestureItemClass.backGroundLight = undefined;
        GameGestureItemClass.ScoreColumn = undefined;
        GameGestureItemClass.headIcoLeft = undefined;
        GameGestureItemClass.headIcoRight = undefined;
        GameGestureItemClass.desk = undefined;
        GameGestureItemClass.foodLeft = undefined;
        GameGestureItemClass.foodRight = undefined;
        GameGestureItemClass.foodMid = undefined;
        GameGestureItemClass.leftHealthCtrlor = undefined;
        GameGestureItemClass.rightHealthCtrlor = undefined;
        GameGestureItemClass.leftHealth = 3;
        GameGestureItemClass.rightHealth = 3;
        GameGestureItemClass.readyState = [0, 0];
        GameGestureItemClass.isOffline = undefined;
        GameGestureItemClass.speedTime = 5000;
        GameGestureItemClass.lineY = 0;
        GameGestureItemClass.isRunning = true;
        GameGestureItemClass.resultPool = [0, 0];
        GameGestureItemClass.runningSec = 0;
        GameGestureItemClass.rightTimeDvalue = undefined;
        GameGestureItemClass.lowestLine = 0;
        GameGestureItemClass.otherlowest = 0;
        GameGestureItemClass.otherLine = undefined;
        GameGestureItemClass.otherLineTW = undefined;
        GameGestureItemClass.AiSuccess = 0;
        GameGestureItemClass.autonomy = undefined;
        GameGestureItemClass.soundWay_1 = undefined;
        GameGestureItemClass.soundWay_2 = undefined;
        GameGestureItemClass.soundWay_3 = undefined;
        GameGestureItemClass.soundWay_num = 1;
        GameGestureItemClass.isLocal = false;
    }
}